name: add-line-to-file

on:
  push:
    branches:
      - main

jobs:
  add_line_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add the line to the file
      - name: Add line to kbmodel.txt
        run: echo "Added in workflow" >> kbmodel.txt
      - name: Add line to gars.txt
        run: echo "Added in workflow" >> gars.txt
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add kbmodel.txt gars.txt
          git commit -m "Added lines to kbmodel.txt and gars.txt"
          git push
