name: add-line-to-file

on:
  push:
    branches:
      - main

jobs:
  add_line_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add the line to the file
      - name: Add line to kbmodel.txt
        run: echo "Added in workflow" >> kbmodel.txt
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "Puja Trivedi"
          git config --global user.email "xspuja@gmail.com"
          git add kbmodel.txt
          git commit -m "Add line to kbmodel.txt"
          git push origin HEAD:main

