name: add-line-to-file

on:
  push:
    branches:
      - main

jobs:
  add_line_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add the line to the file
      - name: Add line to kbmodel.txt
        run: echo "Added in workflow" >> kbmodel.txt
      - name: Commit and push changes
        run: |
          git config --global user.name "Puja Trivedi"
          git config --global user.email "xspuja@gmail.com"
          git add kbmodel.txt
          git commit -m "Add line to kbmodel.txt"
          git push https://github.com/${{ github.repository }}.git HEAD:main
          # You can also use the GH_TOKEN secret like this:
          # git push https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main

