name: push pydantic gars to bkbit

on:
  push:
    paths: 'gars.txt'
  workflow_run:
    workflows: [add-line-to-file]
    types:
      - completed
jobs:
  update_gars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Pushes to another repository
        uses: dmnemec/copy_file_to_another_repo_action@main

        env: 
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'gars.txt'
          destination_repo: 'puja-trivedi/test_workflows_20240510'
          destination_folder: '.'
          user_email: 'xspuja@gmail.com' # the GitHub user email associated with the API token secret.
          user_name: 'puja-trivedi' # the GitHub username associated with the API token secret.
          commit_message: "pydantic version of gars model (gars.txt) was updated. Pushed from brain-bican/model repository"
